# Generated by Django 4.2.25 on 2025-11-15 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_item_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("client", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "expertise",
                    models.CharField(
                        choices=[
                            ("web_apps", "Web Applications"),
                            ("enterprise_saas", "Enterprise SaaS"),
                            ("mobile_apps", "Mobile Applications"),
                            ("geoscience", "Geoscience Platforms"),
                            ("school_mgmt", "School Management Systems"),
                            ("crm", "CRM Solutions"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        help_text="Comma-separated technologies", max_length=300
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="portfolio/"),
                ),
                ("live_url", models.URLField(blank=True, help_text="Live project URL")),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub repository URL"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-completion_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "expertise",
                    models.CharField(
                        choices=[
                            ("web_apps", "Web Applications"),
                            ("enterprise_saas", "Enterprise SaaS"),
                            ("mobile_apps", "Mobile Applications"),
                            ("geoscience", "Geoscience Platforms"),
                            ("school_mgmt", "School Management Systems"),
                            ("crm", "CRM Solutions"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                (
                    "features",
                    models.JSONField(default=list, help_text="List of key features"),
                ),
                (
                    "price_range",
                    models.CharField(
                        blank=True, help_text="e.g. $10k-$50k", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "excerpt",
                    models.TextField(blank=True, help_text="Short preview text"),
                ),
                ("content", models.TextField(help_text="Full post content with HTML")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("news", "Company News"),
                            ("tech", "Technology Updates"),
                            ("case_study", "Case Studies"),
                            ("tutorial", "Tutorials"),
                        ],
                        max_length=50,
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date", "-created_at"],
            },
        ),
    ]
